### ISSUE TITLE
vuepress-plugin-typescript introduce vue-loader problems

### ISSUE THREAD

**Issue by mmc41** [vuepress/vuepress-community#51]
When using vuepress-plugin-typescript v0.3.0 I get strange problems for plain typescript file in my project. The content of the typescript file does not seem to matter. The page appears to work but in the console I get errors like below:

`
[HMR] Waiting for update signal from WDS...
client?cae4:150 [WDS] Errors while compiling. Reload prevented.

[tsl] ERROR in /xxx/docs/.vuepress/jabraService.ts(6,24)
      TS2307: Cannot find module '!../../node_modules/vue-loader/lib/runtime/componentNormalizer.js' or its corresponding 

[tsl] ERROR in /xxx/docs/.vuepress/jabraService.ts(19,20)
      TS2307: Cannot find module './jabraService.ts?vue&type=custom&index=0&blockType=void' or its corresponding type
`

Note that the error is misleading because the jabraService.ts does NOT attempt to load anything vue related like componentNormalizer.

**Comment by mmc41** [comment]
@meteorlxy Should this be assigned to you?

**Comment by meteorlxy** [comment]
@mmc41 Sorry for delay.

Could you please provide a reproduce repo?

**Comment by DamSenViet** [comment]
I ran into the same problem recently and can provide my repository to reproduce the issue.

https://github.com/DamSenViet/acpatterns-js

```bash
git clone https://github.com/DamSenViet/acpatterns-js.git
git checkout 8673e3a07cfd66d2bf5645c736df411ce1d8feb0
npm i
npm run dev:docs
```

**Comment by campbells-snap** [comment]
While not using Vuepress, I had this same issue occur with a Vue-based project.

In my `index.js` file, importing any regular typescript file resolved the issue - I suspect the TypeScript compiler wasn't looking for the ``vue-shims.d.ts` file if it didn't see a reason to do so (and importing a `.vue` file didn't trigger it for whatever reason).

Notably if I start it with the import and then delete it, the debug server continues to work fine.

**Comment by JulioJu** [comment]
Contrary to the example https://github.com/salazarr-js/vuepress-ts, it seems I fix this issue by comment 
```
  "exclude": ["node_modules"]
```
into tsconfig.json.

**Comment by JulioJu** [comment]
This bug is not produced when we trigger `yarn vuepress build docs && yarn anywhere -h localhost -d docs/.vuepress/dist`. It is produced when we trigger
`yarn vuepress dev docs` . The main consequence of this problem is that in this
case there is no Hot Reload (in fact in console we have message
`[WDS] Errors while compiling. Reload prevented.`).

Not that when there was `xxx.ts` file, when we edit this file the bug
disappear for the current `yarn vuepress dev docs` instance. When we restart a new
one, it fails again.

Soulution: **_You could create vue file with only TypeScript elements_**.
Replace your typescript file by a vue file. Surround TypeScript code by a tag
`<script lang="ts">`.
